Fix/phpunit
browserstack/phpunit-browserstack pull request #14
Opened 2023-02-24 04:56 UTC by Ankit098

2023-02-24 07:15 UTC, karanshah-browserstack requested changes

2023-02-24 07:15 UTC, karanshah-browserstack commented on lib/BrowserStackTest.php
> +            print("Starting Local Binary...\n");
Incorrect placement. This will start and stop binary for each test in parallel.php

2023-02-28 05:38 UTC, karanshah-browserstack commented on lib/runner.php
> +    $bs_local = new BrowserStack\Local();
Add comment above to comment this code if you don't need browserstackLocal

2023-02-28 05:58 UTC, karanshah-browserstack approved these changes
LGTM

2023-02-28 11:33 UTC, francisf approved these changes

2023-02-28 11:33 UTC, merged